table train
	lineageTag: d3f6ebd3-a806-43f3-b93d-129e33d4a1c9

	measure 'Total Sales' = sum(train[Sales])
		lineageTag: 70dfa3da-3d0e-4fad-90fa-5485997c7396

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Growth %' =
			
			VAR CurrentYear = SUM('train'[Sales])
			VAR PriorYear = CALCULATE(SUM('train'[Sales]), DATEADD('train'[Order Date], -1, YEAR))
			RETURN DIVIDE(CurrentYear - PriorYear, PriorYear, 0)
		lineageTag: 2d0fc647-1677-4fb4-8598-be6cee6fabf4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 7a373b61-6e1d-4aa1-a8d4-acac47b8e5db
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 0a2d2b17-a075-4f0c-87df-c13daa10b99d
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 77fca5d1-9e80-4fc3-ae7c-6e8f308e4e06
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: a9cb41e6-1bc3-48a9-84b7-4a44e1eb7680
			defaultHierarchy: LocalDateTable_97e601a6-9c11-44e7-adb1-8fa89a308e54.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8c2d4db3-6fe5-4d64-9ee3-40f2b687b878
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 4ed475dc-6d94-48e3-a08d-5db24f686eb7
			defaultHierarchy: LocalDateTable_eb158d36-fa01-49fb-a153-f5a3bac9606c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: e6805e1f-4536-49fc-809c-01d55e8ecade
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 35c6f714-5c6a-4306-9842-bd6833afd619
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 1bb2a375-65e9-48b8-b488-a3382b48a900
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 2ecde597-0c3a-44dd-b964-5134bfc75f49
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d97078b1-b8b4-4d90-a9be-c7dd76c2a490
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 0e42ef73-8db3-45f1-8e0d-9d821d2aa59e
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 7162d209-7506-4d00-8db2-a3242832f5f1
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 20ecbba7-2c3c-483f-8722-ec85155f397e
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 0afaab0d-090d-447f-9d63-da098659c6d3
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 9165478a-545c-4648-b05e-2473b071b834
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 43241346-2604-4908-8f5c-76d521d28cf5
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 0c43053f-18ea-480e-a93b-872095154271
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 44da3c7c-e23a-4e16-af6f-1d360f1457b9
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 46fed1ed-823a-4f9f-aca0-b4b1a4b4fdf0
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: int64
		formatString: 0
		lineageTag: b4c9c808-3bd6-4358-83fb-5260bb168920
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d7b4eb6e-04e5-49fa-8578-b1f5df8c8cef
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: e60373d2-98d4-44ea-9481-f2474c6401c7
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Month-Year
		dataType: string
		lineageTag: 82bf9cb3-3a61-44f7-b9d1-a8bdbe141395
		summarizeBy: none
		sourceColumn: Month-Year

		annotation SummarizationSetBy = Automatic

	partition train = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AMIT ARUN WAGH\OneDrive\Desktop\Data Analyst\Project\project 1\train.csv"),[Delimiter=",", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}}),
				    #"Inserted Month" = Table.AddColumn(#"Changed Type", "Month", each Date.Month([Order Date]), Int64.Type),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Month", "Year", each Date.Year([Order Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([Order Date]), type text),
				    #"Added Custom" = Table.AddColumn(#"Inserted Month Name", "Month-Year", each Date.ToText([Order Date], "MMM yyyy"))
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

